wallpaper {
    monitor = eDP-1
    path = /home/kazz4343/Pictures/Wallpapers/wallhaven-pc.png
    fit_mode = cover,
}

wallpaper {
    monitor = DP-2
    path = /home/kazz4343/Pictures/Wallpapers/wallhaven-pc.png
    fit_mode = cover,
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/kazz4343/Pictures/Wallpapers/wallhaven-pc.png
    fit_mode = cover,
}
